package waffles.utils.sets.utilities;

import waffles.utils.sets.indexed.IndexedSet;
import waffles.utils.sets.indexed.array.ArrayLike;
import waffles.utils.sets.rooted.binary.BiNode;
import waffles.utils.sets.utilities.indexed.iterators.IndexValues;
import waffles.utils.sets.utilities.rooted.iterators.binary.InOrder;
import waffles.utils.sets.utilities.rooted.iterators.binary.PostOrder;
import waffles.utils.sets.utilities.rooted.iterators.binary.PreOrder;

/**
 * The {@code Iterables} class provides static utility methods to generate {@code Iterable} objects.
 * The iterators generated by this class can be applied to the various set structures
 * found within the Collections library.
 * 
 * @author Waffles
 * @since Aug 15, 2015
 * @version 1.0
 */
public final class Iterables
{
	/**
	 * Returns a reverse iterable over an {@code ArrayLike}.
	 * 
	 * @param <O>  an object type
	 * @param set  an array set
	 * @return  a reverse iterable
	 * 
	 * 
	 * @see ArrayLike
	 * @see Iterable
	 */
	public static <O> Iterable<O> reverse(ArrayLike<?, O> set)
	{
		return null;
	}
	
	/**
	 * Returns an iterable over an {@code IndexedSet}.
	 * 
	 * @param <O>  an index object type
	 * @param set  an index set to iterate
	 * @param min  a minimum coordinate
	 * @param max  a maximum coordinate
	 * @return  an index iterable
	 * 
	 * 
	 * @see IndexedSet
	 * @see Iterable
	 */
	public static <O> Iterable<O> index(IndexedSet<O> set, int[] min, int[] max)
	{
		return () -> new IndexValues<>(set, min, max);
	}
		
	
	/**
	 * Returns an in-order iterable over a {@code BiNode}.
	 * 
	 * @param <N>  a node type
	 * @param base  a base node
	 * @return  an in-order iterable
	 * 
	 * 
	 * @see Iterable
	 * @see BiNode
	 */
	public static <N extends BiNode> Iterable<N> inorder(N base)
	{
		return () -> new InOrder<>(base);
	}
	
	/**
	 * Returns a post-order iterable over a {@code BiNode}.
	 * 
	 * @param <N>  a node type
	 * @param base  a base node
	 * @return  a post-order iterable
	 * 
	 * 
	 * @see Iterable
	 * @see BiNode
	 */
	public static <N extends BiNode> Iterable<N> postorder(N base)
	{
		return () -> new PostOrder<>(base);
	}
	
	/**
	 * Returns a pre-order iterable over a {@code BiNode}.
	 * 
	 * @param <N>  a node type
	 * @param base  a base node
	 * @return  a pre-order iterable
	 * 
	 * 
	 * @see Iterable
	 * @see BiNode
	 */
	public static <N extends BiNode> Iterable<N> preorder(N base)
	{
		return () -> new PreOrder<>(base);
	}
	
	
	private Iterables()
	{
		// NOT APPLICABLE
	}
}
